### ISSUE TITLE
wrong day names when using firstDay 

### ISSUE THREAD

**Issue by ronald** [Innologica/vue2-daterange-picker#96] opened 2019-10-10 14:25 UTC
Thx for building and providing vue2-daterange-picker
We have some trouble using version 0.3.1 with "firstDay"-Option

`"daysOfWeek": ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
"firstDay: 0`
we get what we expect: Su Mo Tu We Th Fr Sa

But if you set `  "firstDay": 1`
expected result:  Mo Tu We Th Fr Sa Su
current result: Tu We Th Fr Sa Su Mo

**Comment by nkostadinov** [comment] 2019-10-11 05:40
hm, I'll check this but I'm using firstDay:1 myself and dont seem to have any trouble. Do you pass daysOfWeek also ? Can you provide locale-data that you pass to the component ?

**Comment by ronald** [comment] 2019-10-11 07:34
I see. It works if we hard code i18n

```html
  <date-range-picker class="vue-daterange-picker w-100 d-block"
                     @update="updatePicker"
                     :ranges="ranges"
                     :locale-data="locale"
                     :autoApply="!timePicker"
                     :minDate="minDate"
                     :singleDatePicker="singleDatePicker"
                     :timePicker="timePicker"
                     :timePicker24Hour="true"
                     :time-picker-increment="15"
                     v-model="dateRange"
          >
    <div slot="input">
      <i class="icon far fa-calendar-alt"></i>
      <span class="text">{{step.text}}</span>
      <span class="duration">{{step.duration}}</span>
      <input v-model="step.checkin" type="hidden" name="checkin" class="start" />
      <input v-model="step.checkout" type="hidden" name="checkout" class="end" /></div>
  </date-range-picker>
```
```javascript
data() {
            return {
  "locale": {
    "format": "DD.MM.YYYY",
    "separator": " - ",
    "applyLabel": "Ok",
    "cancelLabel": "Abbrechen",
    "fromLabel": "Von",
    "toLabel": "Bis",
    "customRangeLabel": "Custom",
    "weekLabel": "W",
    "daysOfWeek": [
      "Sa",
      "So",
      "Mo",
      "Di",
      "Mi",
      "Do",
      "Fr"
    ],
    "monthNames": [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember"
    ],
    "firstDay": 1
  },
  "minDate": "2019-10-11T07:10:35.144Z",
  "ranges": false,
  "timePicker24Hour": true,
  "dateRange": {}
}
        },

```


If we we use 
```daysOfWeek: this.$store.state.i18n.daysOfWeek```
the code https://github.com/Innologica/vue2-daterange-picker/blob/bb9c8291a3f6166058faebde0a324f9457ca1f53/src/components/DateRangePicker.vue#L311
mutates the i18n config.

**Comment by ronald** [comment] 2019-10-11 07:38
We now fixed it by copying the array:

`"daysOfWeek": [...this.$store.state.i18n.daysOfWeek],`

**Comment by nkostadinov** [comment] 2019-10-11 07:40
If you pass daysOfWeek the array should start with Sunday. I beleive thats the problem.

**Comment by ronald** [comment] 2019-10-11 07:41
> If you pass daysOfWeek the array should start with Sunday. I beleive thats the problem.

Sorry, the example was wrong. This was the first hotfix. 
I corrected the example above.

**Comment by nkostadinov** [comment] 2019-10-11 07:44
Yes, I modify the array when you use firstDayOfWeek > 0. May be I will change it to make internally a copy of the prop. 
I will check you example when I have time to see if there is an issue.

**Comment by ala747** [comment] 2019-11-04 10:31
Hi there! I've had the same behavior but I discovered it only happens (to me at least) when I'm using the picker two times in the same component using the same `locale` object, i.e.:
```
      locale: {
        direction: 'ltr',
        format: 'YYYY-MM-DD',
        separator: ' - ',
        applyLabel: this.$gettext('Apply'),
        cancelLabel: this.$gettext('Cancel'),
        weekLabel: 'W',
        customRangeLabel: 'Custom Range',
        daysOfWeek: this.moment.weekdaysMin(),
        monthNames: this.moment.monthsShort(),
        firstDay: this.moment().day(0) === this.moment().local().weekday(0) ? 0 : 1,
        showWeekNumbers: false
      }
```
The current workaround was, obviously, using two `locale` objects (with the same data tho) but I think if you make an internal copy of the prop it should work as expected.

**Comment by nkostadinov** [comment] 2019-11-04 12:23
yes. the problem is that the component modifies the object. One way to avoid this is to use the spread operator e.g.  `:locale-data="{...locale}"`

**Comment by nkostadinov** [comment] 2019-12-17 06:48
This is fixed now in the master branch. Will soon release a new version with the fix.

**Closed by nkostadinov** 2019-12-17 06:48 UTC
