### ISSUE TITLE
Calendars padding causes display errors

### ISSUE THREAD

**Issue by MounirOnGithub** [Innologica/vue2-daterange-picker#56] opened 2019-05-03 07:40 UTC
Hello there, my calendars does not display ltr correctly because of its padding, here is some screenshot that shows it :

![Capture d’écran 2019-05-03 à 09 34 29](https://user-images.githubusercontent.com/15196051/57124812-74da8000-6d87-11e9-86bd-3fda049d594d.png)
![Capture d’écran 2019-05-03 à 09 34 06](https://user-images.githubusercontent.com/15196051/57124813-75731680-6d87-11e9-96f2-87021add2c4c.png)

**Comment by nkostadinov** [comment] 2019-06-24 07:28
could you try the last version if the problem persist. If the problem is still there may be there is a style in your site which causes it. Can you provide jsfiddle or something

**Comment by nkostadinov** [comment] 2019-06-26 09:44
This should be fixed in v0.3.0, if the problem persist please attach a fiddle or something that will help me identify the issue easier.

**Closed by nkostadinov** 2019-06-26 09:44 UTC

**Comment by MounirOnGithub** [comment] 2019-08-17 18:39
OK I'll let you know, sorry for this late answer :/
