### ISSUE TITLE
Wrong range active class applied in date picker. 

### ISSUE THREAD

**Issue by Jay427** [Innologica/vue2-daterange-picker#158] opened 2020-04-27 11:38 UTC
![image](https://user-images.githubusercontent.com/23294684/80365983-1797e280-88a6-11ea-892e-ed4401c8f2c0.png)

- I set to default 6 hours range in the date picker but when select 6 hours range from date picker active class auto-applied in **Custom Range** option and **Last Hour** option.

- Date range picker component option.
`<date-range-picker
        :opens="opens"
        :startDate="startDate"
        :endDate="endDate"
        @update="submitted"
        :locale-data="{ firstDay: 1, format: 'DD-MM-YYYY HH:mm z' }"
        :minDate="minDate"
        :maxDate="maxDate"
        :singleDatePicker="singleDatePicker"
        :timePicker="timePicker"
        :timePicker24Hour="timePicker24Hour"
        :autoApply="autoApply"
        v-model="dateRange"
        :ranges="ranges"
        :date-util="customOption"
      >`

- Date picker state
```
{
      opens: "right",
      startDate: moment()
        .tz(timezone)
        .subtract(30, "days"),
      endDate: moment().tz(timezone),
      minDate: "2019-01-01",
      maxDate: "2022-01-01",
      dateRange: {
        startDate: moment()
          .tz(timezone)
          .subtract(6, "hours"),
        endDate: moment().tz(timezone)
      },
      show_ranges: true,
      singleDatePicker: false,
      timePicker: true,
      timePicker24Hour: true,
      showDropdowns: true,
      autoApply: false,
      showWeekNumbers: true,
      ranges: {
        "Last Hour": [moment().tz(timezone).subtract(1, "hours"),moment().tz(timezone)],
        "Last 6 Hours": [moment().tz(timezone).subtract(6, "hours"),moment().tz(timezone)],
        "Last 24 Hours": [moment().tz(timezone).subtract(1, "days"),moment().tz(timezone)],
        "Last 3 Days": [moment().tz(timezone).subtract(3, "days"),moment().tz(timezone)],
        "Last week": [moment().tz(timezone).subtract(1, "week"),moment().tz(timezone)],
        "Last month": [moment().tz(timezone).subtract(1, "months"),moment().tz(timezone)],
        "Custom Range": [moment().tz(timezone), moment().tz(timezone)]
      },
      customOption: {
        isSame: (date1, date2, granularity = "date") => {
          return moment(date1).isSame(date2, granularity);
        },
        daysInMonth: (year, month) => {
          return moment([year, month]).daysInMonth();
        },
        weekNumber: date => {
          return moment(date).week();
        },
        format: (date, mask) => {
          return moment(date).tz(timezone).format(mask);
        },
        nextMonth: date => {
          return moment(date)
            .add(1, "months")
            .startOf("month")
            .toDate();
        },
        prevMonth: date => {
          return moment(date)
            .subtract(1, "months")
            .startOf("month")
            .toDate();
        },
        validateDateRange: (newDate, min, max) => {
          let max_date = new Date(max);
          let min_date = new Date(min);

          if (max && moment(newDate).isAfter(max_date)) {
            return max_date;
          }

          if (min && moment(newDate).isBefore(min_date)) {
            return min_date;
          }

          return newDate;
        },
        localeData: options => {
          let default_locale = {
            direction: "ltr",
            format: moment.localeData().longDateFormat("L"),
            separator: " - ",
            applyLabel: "Apply",
            cancelLabel: "Cancel",
            weekLabel: "W",
            customRangeLabel: "Custom Range",
            daysOfWeek: moment.weekdaysMin(),
            monthNames: moment.monthsShort(),
            firstDay: moment.localeData().firstDayOfWeek()
          };

          return { ...default_locale, ...options };
        },
        yearMonth: date => {
          return moment(date).format("YYYYMM");
        },
        isValidDate: d => {
          return moment(d).isValid();
        }
      }
    }
```
- Hope you understand my issue.
Advance Thanks,

**Comment by nkostadinov** [comment] 2020-05-03 09:36
Duplicate of #160 . I made a fix in the latest version.

**Closed by nkostadinov** 2020-05-03 09:36 UTC
